version: "3.8"
services:
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: web_app
    ports:
      - "3000:3000"
    env_file:
      - ./server/.env # or ./.env if your env is in the root
    depends_on:
      - db
    volumes:
      - ./server:/app
      - /app/node_modules

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432" # maps container's 5432 to host's 5433

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
